### ISSUE TITLE
Monitor: View Grafana / AlertManager- site cannot be reached

### ISSUE THREAD

**Issue by skdwriting** [opensds/opensds-dashboard#129]
GUI->login->Monitor->View Grafana
It goes to http://localhost:3000/
Then throws error : The Site cannot be reached.

GUI->login->Monitor->View AlertManager
It goes to http://localhost:9093/
Then throws error : The Site cannot be reached.

If you give host ip, it works.

Suggestion:
Please handle it automatically with the hostip.

**Comment by anvithks** [comment]
@skdwriting this is fixed in latest code. I believe you are using an older release cut which had the issues listed by you. 
Could you please share the install config used by you in the common.yml file. Specifically the following information:  
```yml
# This field indicates which way user prefers to install, currently support
# 'repository', 'release' and 'container'
install_from: 
# These fields below will specify the tag based on install_from type
repo_branch: 
release_version: 
image_tag: 
```
